file <- read.csv('../Q57.csv')
#file <- file[c('Program','entry2553_GPAX','Math','Science','English','X2557_GPAX')]
names(file)[7] <- paste("GPAX")
file$Program <- ifelse(file$Program=='วิศวกรรมเครื่องกล','Mechanical Engineering',ifelse(file$Program=='วิศวกรรมโยธา','Civil Engineering',ifelse(file$Program=='วิศวกรรมสิ่งแวดล้อม','Environmental Engineering',ifelse(file$Program=='วิศวกรรมไฟฟ้า','Electrical Engineering',ifelse(file$Program=='วิศวกรรมอุตสาหการ','Industrial Engineering',ifelse(file$Program=='วิศวกรรมเคมีและชีวภาพ','Chemical & Biological Engineering','No'))))))
file <- unique(file)
write.csv(file, file='clean_57.csv',row.names=FALSE)
print("Mechanical Engineering")
print(nrow(subset(file,Program=='Mechanical Engineering')))
print("Civil Engineering")
print(nrow(subset(file,Program=='Civil Engineering')))
print("Environmental Engineering")
print(nrow(subset(file,Program=='Environmental Engineering')))
print("Electrical Engineering")
print(nrow(subset(file,Program=='Electrical Engineering')))
print("Chemical & Biological Engineering")
print(nrow(subset(file,Program=='Chemical & Biological Engineering')))
