file <- read.csv('source_kmean.csv')
C1 <- ifelse(file$Province=="กาฬสินธุ์","P1","0")
C2 <- ifelse(file$Province=="อุบลราขธานี","P2",C1)
C3 <- ifelse(file$Province=="อำนาจเจริญ","P3",C2)
C4 <- ifelse(file$Province=="หนองบัวลำภู","P4",C3)
C5 <- ifelse(file$Province=="นครพนม","P5",C4)
C6 <- ifelse(file$Province=="สุรินทร์","P6",C5)
C7 <- ifelse(file$Province=="ร้อยเอ็ด","P7",C6)
C8 <- ifelse(file$Province=="หนองคาย","P8",C7)
C9 <- ifelse(file$Province=="ศรีสะเกษ","P9",C8)
C10 <- ifelse(file$Province=="ขอนแก่น","P10",C9)
C11 <- ifelse(file$Province=="ยโสธร","P11",C10)
C12 <- ifelse(file$Province=="อุดรธานี","P12",C11)
C13 <- ifelse(file$Province=="ชัยภูมิ","P13",C12)
C14 <- ifelse(file$Province=="มุกดาหาร","P14",C13)
C15 <- ifelse(file$Province=="เลย","P15",C14)
C16 <- ifelse(file$Province=="บุรีีรัมย","P16",C15)
C17 <- ifelse(file$Province=="นครราชสีมา","P17",C16)
C18 <- ifelse(file$Province=="สกลนคร","P18",C17)
C19 <- ifelse(file$Province=="สระแก้ว","P19",C18)
C20 <- ifelse(file$Province=="บึงกาฬ","P20",C19)
C21 <- ifelse(file$Province=="สมุทรปราการ","P21",C20)
C22 <- ifelse(file$Province=="มหาสารคาม","P22",C21)
C23 <- ifelse(file$Province=="นนทบุรี","P23",C22)
C24 <- ifelse(file$Province=="ชลบุรี","P24",C23)
C25 <- ifelse(file$Province=="กรุงเทพมหานคร","P25",C24)
C26 <- ifelse(file$Province=="สระบุรี","P26",C25)
C27 <- ifelse(file$Province=="เพชรบูรณ์","P27",C26)
C28 <- ifelse(file$Province=="เพชรบุรี","P28",C27)
C29 <- ifelse(file$Province=="สมุทรสาคร","P29",C28)
C30 <- ifelse(file$Province=="น่าน","P30",C29)
C31 <- ifelse(file$Province=="สงขลา","P31",C30)
C32 <- ifelse(file$Province=="กาญจนบุรี","P32",C31)
C33 <- ifelse(file$Province=="ชัยนาท","P33",C32)
file$Province <- ifelse(file$Province=="เชียงใหม่","P34",C33)
print(nrow(file))
print("P1")
print(nrow(subset(file,Province=='P1')))
print("P2")
print(nrow(subset(file,Province=='P2')))
print("P3")
print(nrow(subset(file,Province=='P3')))
print("P4")
print(nrow(subset(file,Province=='P4')))
print("P5")
print(nrow(subset(file,Province=='P5')))
print("P6")
print(nrow(subset(file,Province=='P6')))
print("P7")
print(nrow(subset(file,Province=='P7')))
print("P8")
print(nrow(subset(file,Province=='P8')))
print("P9")
print(nrow(subset(file,Province=='P9')))
print("P10")
print(nrow(subset(file,Province=='P10')))
print("P11")
print(nrow(subset(file,Province=='P11')))
print("P12")
print(nrow(subset(file,Province=='P12')))
print("P13")
print(nrow(subset(file,Province=='P13')))
print("P14")
print(nrow(subset(file,Province=='P14')))
print("P15")
print(nrow(subset(file,Province=='P15')))
print("P16")
print(nrow(subset(file,Province=='P16')))
print("P17")
print(nrow(subset(file,Province=='P17')))
print("P18")
print(nrow(subset(file,Province=='P18')))
print("P19")
print(nrow(subset(file,Province=='P19')))
print("P20")
print(nrow(subset(file,Province=='P20')))
print("P21")
print(nrow(subset(file,Province=='P21')))
print("P22")
print(nrow(subset(file,Province=='P22')))
print("P23")
print(nrow(subset(file,Province=='P23')))
print("P24")
print(nrow(subset(file,Province=='P24')))
print("P25")
print(nrow(subset(file,Province=='P25')))
print("P26")
print(nrow(subset(file,Province=='P26')))
print("P27")
print(nrow(subset(file,Province=='P27')))
print("P28")
print(nrow(subset(file,Province=='P28')))
print("P29")
print(nrow(subset(file,Province=='P29')))
print("P30")
print(nrow(subset(file,Province=='P30')))
print("P31")
print(nrow(subset(file,Province=='P31')))
print("P32")
print(nrow(subset(file,Province=='P32')))
print("P33")
print(nrow(subset(file,Province=='P33')))
print("P34")
print(nrow(subset(file,Province=='P34')))
print("0")
print(nrow(subset(file,Province=='0')))
