file <- read.csv('../Q57.csv')
file <- file[c('entry2553_GPAX','Math','Science','English','X2557_GPAX')]
#file$Program <- ifelse(file$Program=='วิศวกรรมเครื่องกล','Mechanical Engineering',ifelse(file$Program=='วิศวกรรมโยธา','Civil Engineering',ifelse(file$Program=='วิศวกรรมสิ่งแวดล้อม','Environmental Engineering',ifelse(file$Program=='วิศวกรรมไฟฟ้า','Electrical Engineering',ifelse(file$Program=='วิศวกรรมอุตสาหการ','Industrial Engineering',ifelse(file$Program=='วิศวกรรมเคมีและชีวภาพ','Chemical & Biological Engineering','No'))))))
names(file)[1] <- paste("graduate_GPAX")
names(file)[5] <- paste("entrance_GPAX")
#Entrance_GPAX
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=0.0, 1, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=0.5, 2, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=1.0, 3, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=1.5, 4, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=2.0, 5, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=2.5, 6, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=3.0, 7, file$entrance_GPAX_G)
file$entrance_GPAX_G <- ifelse(file$entrance_GPAX>=3.5, 8, file$entrance_GPAX_G)
#Math
file$Math_G <- ifelse(file$Math>=0.0, 1, file$Math_G)
file$Math_G <- ifelse(file$Math>=0.5, 2, file$Math_G)
file$Math_G <- ifelse(file$Math>=1.0, 3, file$Math_G)
file$Math_G <- ifelse(file$Math>=1.5, 4, file$Math_G)
file$Math_G <- ifelse(file$Math>=2.0, 5, file$Math_G)
file$Math_G <- ifelse(file$Math>=2.5, 6, file$Math_G)
file$Math_G <- ifelse(file$Math>=3.0, 7, file$Math_G)
file$Math_G <- ifelse(file$Math>=3.5, 8, file$Math_G)
#Science
file$Science_G <- ifelse(file$Science>=0.0, 1, file$Science_G)
file$Science_G <- ifelse(file$Science>=0.5, 2, file$Science_G)
file$Science_G <- ifelse(file$Science>=1.0, 3, file$Science_G)
file$Science_G <- ifelse(file$Science>=1.5, 4, file$Science_G)
file$Science_G <- ifelse(file$Science>=2.0, 5, file$Science_G)
file$Science_G <- ifelse(file$Science>=2.5, 6, file$Science_G)
file$Science_G <- ifelse(file$Science>=3.0, 7, file$Science_G)
file$Science_G <- ifelse(file$Science>=3.5, 8, file$Science_G)
#English
file$English_G <- ifelse(file$English>=0.0, 1, file$English_G)
file$English_G <- ifelse(file$English>=0.5, 2, file$English_G)
file$English_G <- ifelse(file$English>=1.0, 3, file$English_G)
file$English_G <- ifelse(file$English>=1.5, 4, file$English_G)
file$English_G <- ifelse(file$English>=2.0, 5, file$English_G)
file$English_G <- ifelse(file$English>=2.5, 6, file$English_G)
file$English_G <- ifelse(file$English>=3.0, 7, file$English_G)
file$English_G <- ifelse(file$English>=3.5, 8, file$English_G)
#Graduate_GPAX
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=0.0, 1, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=0.5, 2, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=1.0, 3, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=1.5, 4, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=2.0, 5, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=2.5, 6, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=3.0, 7, file$graduate_GPAX_G)
file$graduate_GPAX_G <- ifelse(file$graduate_GPAX>=3.5, 8, file$graduate_GPAX_G)
file <- file[c('entrance_GPAX_G','Math_G','Science_G','English_G','graduate_GPAX_G')]
names(file)[1] <- paste("Entrance_GPAX")
names(file)[2] <- paste("Math_GPA")
names(file)[3] <- paste("Science_GPAX")
names(file)[4] <- paste("English_GPAX")
names(file)[5] <- paste("Graduate_GPAX")
#file <- unique(file)
write.csv(file, file='clean_57.csv',row.names=FALSE)
print("57 - Finished!!!")
