file53 <- read.csv('53SUBPRO.csv')
file54 <- read.csv('54SUBPRO.csv')
file55 <- read.csv('55SUBPRO.csv')
file56 <- read.csv('56SUBPRO.csv')
file57 <- read.csv('57SUBPRO.csv')
res1 <- rbind(file53,file54)
res2 <- rbind(file55,file56)
res3 <- rbind(res1,res2)
res4 <- rbind(res3,file57)
#res4 <- unique(res4)
res4 <- subset(res4, Program!='No')
res4 <- subset(res4, Thai_G!=1)
res4 <- subset(res4, PhysicalAct_G!=1)
res4 <- subset(res4, Math_G!=1)
res4 <- subset(res4, Art_G!=1)
res4 <- subset(res4, Science_G!=1)
res4 <- subset(res4, Industrial_G!=1)
res4 <- subset(res4, Social_G!=1)
res4 <- subset(res4, English_G!=1)
write.csv(res4,file='source_ml_sub_pro.csv',row.names=FALSE)
