args <- commandArgs(TRUE)
path <- args[1]
file <- read.csv(path)
file <- file[c('entry2553_GPAX','Thai','PhysicalAct','Math','Art','Science','Industrial','Social','English','Program')]
names(file)[1] <- paste("GPAX")
file$Program <- ifelse(file$Program=='วิศวกรรมเครื่องกล','Mechanical Engineering',ifelse(file$Program=='วิศวกรรมโยธา','Civil Engineering',ifelse(file$Program=='วิศวกรรมสิ่งแวดล้อม','Environmental Engineering',ifelse(file$Program=='วิศวกรรมไฟฟ้า','Electrical Engineering',ifelse(file$Program=='วิศวกรรมอุตสาหการ','Industrial Engineering',ifelse(file$Program=='วิศวกรรมเคมีและชีวภาพ','Chemical & Biological Engineering','No'))))))
#Thai
file$Thai_G <- ifelse(file$Thai>=0.0, 1, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=0.5, 2, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=1.0, 3, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=1.5, 4, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=2.0, 5, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=2.5, 6, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=3.0, 7, file$Thai_G)
file$Thai_G <- ifelse(file$Thai>=3.5, 8, file$Thai_G)
#PhysicalAct
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=0.0, 1, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=0.5, 2, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=1.0, 3, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=1.5, 4, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=2.0, 5, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=2.5, 6, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=3.0, 7, file$PhysicalAct_G)
file$PhysicalAct_G <- ifelse(file$PhysicalAct>=3.5, 8, file$PhysicalAct_G)
#Math
file$Math_G <- ifelse(file$Math>=0.0, 1, file$Math_G)
file$Math_G <- ifelse(file$Math>=0.5, 2, file$Math_G)
file$Math_G <- ifelse(file$Math>=1.0, 3, file$Math_G)
file$Math_G <- ifelse(file$Math>=1.5, 4, file$Math_G)
file$Math_G <- ifelse(file$Math>=2.0, 5, file$Math_G)
file$Math_G <- ifelse(file$Math>=2.5, 6, file$Math_G)
file$Math_G <- ifelse(file$Math>=3.0, 7, file$Math_G)
file$Math_G <- ifelse(file$Math>=3.5, 8, file$Math_G)
#Art
file$Art_G <- ifelse(file$Art>=0.0, 1, file$Art_G)
file$Art_G <- ifelse(file$Art>=0.5, 2, file$Art_G)
file$Art_G <- ifelse(file$Art>=1.0, 3, file$Art_G)
file$Art_G <- ifelse(file$Art>=1.5, 4, file$Art_G)
file$Art_G <- ifelse(file$Art>=2.0, 5, file$Art_G)
file$Art_G <- ifelse(file$Art>=2.5, 6, file$Art_G)
file$Art_G <- ifelse(file$Art>=3.0, 7, file$Art_G)
file$Art_G <- ifelse(file$Art>=3.5, 8, file$Art_G)
#Science
file$Science_G <- ifelse(file$Science>=0.0, 1, file$Science_G)
file$Science_G <- ifelse(file$Science>=0.5, 2, file$Science_G)
file$Science_G <- ifelse(file$Science>=1.0, 3, file$Science_G)
file$Science_G <- ifelse(file$Science>=1.5, 4, file$Science_G)
file$Science_G <- ifelse(file$Science>=2.0, 5, file$Science_G)
file$Science_G <- ifelse(file$Science>=2.5, 6, file$Science_G)
file$Science_G <- ifelse(file$Science>=3.0, 7, file$Science_G)
file$Science_G <- ifelse(file$Science>=3.5, 8, file$Science_G)
#Industrial
file$Industrial_G <- ifelse(file$Industrial>=0.0, 1, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=0.5, 2, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=1.0, 3, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=1.5, 4, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=2.0, 5, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=2.5, 6, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=3.0, 7, file$Industrial_G)
file$Industrial_G <- ifelse(file$Industrial>=3.5, 8, file$Industrial_G)
#Social
file$Social_G <- ifelse(file$Social>=0.0, 1, file$Social_G)
file$Social_G <- ifelse(file$Social>=0.5, 2, file$Social_G)
file$Social_G <- ifelse(file$Social>=1.0, 3, file$Social_G)
file$Social_G <- ifelse(file$Social>=1.5, 4, file$Social_G)
file$Social_G <- ifelse(file$Social>=2.0, 5, file$Social_G)
file$Social_G <- ifelse(file$Social>=2.5, 6, file$Social_G)
file$Social_G <- ifelse(file$Social>=3.0, 7, file$Social_G)
file$Social_G <- ifelse(file$Social>=3.5, 8, file$Social_G)
#English
file$English_G <- ifelse(file$English>=0.0, 1, file$English_G)
file$English_G <- ifelse(file$English>=0.5, 2, file$English_G)
file$English_G <- ifelse(file$English>=1.0, 3, file$English_G)
file$English_G <- ifelse(file$English>=1.5, 4, file$English_G)
file$English_G <- ifelse(file$English>=2.0, 5, file$English_G)
file$English_G <- ifelse(file$English>=2.5, 6, file$English_G)
file$English_G <- ifelse(file$English>=3.0, 7, file$English_G)
file$English_G <- ifelse(file$English>=3.5, 8, file$English_G)
file <- file[c('GPAX','Thai_G','PhysicalAct_G','Math_G','Art_G','Science_G','Industrial_G','Social_G','English_G','Program')]
outputPath <- args[2]
write.csv(file,file=outputPath,row.names=FALSE)
